version: "3.3"
services:
  
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainerdata:/data"
    networks:
      - backend  
    deploy:
      placement:
        constraints: [node.role == manager]
    labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=Host:portainer.docker.localhost"
        - "traefik.enable=true"
        - "traefik.port=9000"

  ms1:
    image: melvindave/spring-boot-example
    ports: 
      - "8080:8080"
    networks:
      - backend
    depends_on: 
      - mongodb
    deploy:
      replicas: 1
    labels:
        - "traefik.backend=ms1"
        - "traefik.frontend.rule=Host:ms1.docker.localhost"
        - "traefik.enable=true"
        - "traefik.port=8080"

  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - backend  
    deploy:
      replicas: 1    

  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - frontend      
    deploy:
      replicas: 1  

networks:
  frontend:
  backend:

volumes:
   mongodata:
   portainerdata:
