version: "3.5"

services:
    pihole:
        image: pihole/pihole:latest
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "8000:80/tcp"
            - "443:443/tcp"
        volumes:
            - pihole-data:/etc/pihole
            - dnsmasq-data:/etc/dnsmasq.d
        environment:
            - TZ=UTC
            - ServerIp=127.0.0.1
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

volumes:
    pihole-data: {}
    dnsmasq-data: {}
