version: "3"
services:

  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    deploy:
      replicas: 1

  tomcat:
    image: 'tomcat:9'
    ports:
      - '8080:8080'
    networks:
      - frontend
    deploy:
      replicas: 1

  elasticsearch:
    image: 'elasticsearch:5'
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend
    deploy:
      replicas: 1

  kibana:
    image: 'kibana:5'
    ports:
      - "5601:5601"
    networks:
      - backend
    depends_on:
      - elasticsearch    
    deploy:
      replicas: 1

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]
  
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - frontend  
    deploy:
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis
    ports:
        - "6379:6379"  
    networks:
      - backend

  mongodb:  
    image: mongo:3.4
    ports:
      - "27017:27017"  
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
   dbdata:
   