version: "3.1"

services:
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    dbPostgres:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: changeme
            POSTGRES_DB: mydb
    dbMysql:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: mydb
    dbMongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: changeme
