version: "3.1"

services:
    dbPostgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: changeme
            POSTGRES_DB: mydb
    dbMysql:
        container_name: mysql
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: mydb
    dbMongodb:
        container_name: mongodb
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: changeme
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - 8181:80
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: changeme
            PMA_HOST: mysql
            PMA_PORT: 3306
