version: "3.5"

services:
    pihole:
        image: pihole/pihole:debian_armhf
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "80:80/tcp"
            - "443:443/tcp"
        volumes:
            - pihole-data:/etc/pihole
            - dnsmasq-data:/etc/dnsmasq.d
        environment:
            - TZ=UTC
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

volumes:
    pihole-data: {}
    dnsmasq-data: {}
